site_name: 博慎的數位花園
site_url: https://www.marvin-elsen.com
site_description: Marvin Elsen is a passionate German software engineer and InfoSec-enthusiast. Empowering people through exceptional, great-looking and secure software is what drives him to become his greatest version.
# keywords: Marvin Elsen, Marvin, Elsen, Germany, Trier, software developer, developer, software engineer, UX, user experience, user interface, usability, InfoSec, NetSec, IT security, security, information security, cryptography, data protection, data privacy, privacy, Java, Java 11, Python, Kotlin, Android, mobile development, mobile, app development, programming, coding
site_author: Marvin Elsen
# copyright: Copyright &copy; 2020 Marvin Elsen
copyright: "<a rel=\"license\" href=\"http://creativecommons.org/publicdomain/zero/1.0/\"> <img src=\"https://licensebuttons.net/p/zero/1.0/80x15.png\" style=\"border-style: none;\" alt=\"CC0\" /> </a><br>To the extent possible under law, Marvin Elsen has waived all copyright and related or neighboring rights to the written content of this website"
docs_dir: vimwiki
site_dir: site
repo_url: https://github.com/elsenm/digital-garden
repo_name: elsenm/digital-garden
edit_uri: ""
nav:
    - Introduction: index.md
    - Chinese:
        - Overview: overview.md
        - Zhuyin: zhuyin.md
    - Programming:
        - Overview: overview.md
        - Python: python.md
        - Java: java.md
    - Software:
        - Overview: overview.md
        - Toolbox: toolbox.md
        - vim: vim.md
    - Troubleshoot:
        - Overview: overview.md
theme:
    name: material
    favicon: images/favicon.ico
    icon:
        repo: fontawesome/brands/github-alt
    features:
        - instant
        - tabs
    palette:
        #scheme: youtube
    font:
        text: Roboto
        code: Roboto Mono
    language: en
extra_css:
    - stylesheets/extra.css
plugins:
    - search
    - minify:
        minify_html: true
    - git-revision-date
markdown_extensions:
    - meta
    - toc:
        permalink: "#"
        baselevel: 2
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@marvin-elsen.com
      name: Send me an eMail

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/elsen_marvin
      name: Follow me on Twitter

    - icon: fontawesome/brands/keybase
      link: https://keybase.io/elsenm
      name: Send me an encrypted message on Keybase

    - icon: fontawesome/brands/github
      link: https://github.com/elsenm
      name: Take a look at my code over on GitHub

    - icon: fontawesome/brands/stack-exchange
      link: https://stackexchange.com/users/16526518/elsenm
      name: View my Stack Exchange profile

    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/cv/marvin-elsen
      name: View my Stack Overflow profile

    - icon: fontawesome/brands/xing
      link: https://www.xing.com/profile/Marvin_Elsen2
      name: Connect with me on XING

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marvin-elsen
      name: Connect with me on LinkedIn

    - icon: fontawesome/brands/line
      link: https://line.me/ti/p/fw6_p8JvX_
      name: Chat with me on LINE

    - icon: fontawesome/regular/comment-dots
      link: https://threema.id/MF5ZZ4RB
      name: Chat with me on Threema

    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/elsenm
      name: Follow me on reddit
